---
- name: "Instalando pacotes do sistema nescessarios para o Apache2 e PHP5"
  apt:
    name:
      [
        "php5",
        "apache2",
        "libapache2-mod-php5",
        "php5-gd",
        "libssh2-php",
        "php5-mcrypt",
        "php5-mysql",
      ]
    state: latest
  become: yes