---
- name: "Fazendo download da versão 5.0 do wordpress"
  get_url:
    url: https://wordpress.org/wordpress-5.0.tar.gz
    dest: "/tmp/wordpress.tar.gz"

- name: "Descompactando arquivo do wordpress"
  unarchive:
    src: "/tmp/wordpress.tar.gz"
    dest: "/var/www/"
    remote_src: yes
  become: yes

- name: "Fazendo uma cópia do arquivo de exemplo de configuração do wordpress"
  copy:
    src: "{{ WORDPRESS_DIR }}/wp-config-sample.php"
    dest: "{{ WORDPRESS_DIR }}/wp-config.php"
    remote_src: yes
  become: yes

- name: "Substituindo variaveis de ambiente no arquivo de configuração do wordpress"
  replace:
    path: "{{ WORDPRESS_DIR }}/wp-config.php"
    regexp: "{{ item.regex }}"
    replace: "{{ item.value }}"
  with_items:
    - { regex: "database_name_here", value: "{{ DATABASE_NAME }}" }
    - { regex: "username_here", value: "{{ DATABASE_USER }}" }
    - { regex: "password_here", value: "{{ DATABASE_PASSWORD }}" }
    - { regex: "localhost", value: "{{ HOST_MYSQL }}" }
  become: yes

- name: "Copiando arquivo de configuração do apache"
  template:
    src: "../templates/000-default.conf.j2"
    dest: "/etc/apache2/sites-available/000-default.conf"
  become: yes
  notify:
    - restart apache